### ISSUE TITLE
Endringer i responsiv implementasjon

### ISSUE THREAD

**Issue by MatsAnd** [vtfk/minelev-web#48]
Hentet fra: https://github.com/vtfk/vtfk-minelev-react/pull/44#pullrequestreview-535321549

---

- [x] Klikk på utsiden av sidemenyen bør lukke menyen.
- [x] Ikke mulig å scrolle i sidemenyen - bør det være det..? 
- [x] Bør søkeboksen gjøres bredere i mobilvisning, slik at det er like mye avstand på begge sider?
- [x] Legger man telefonen i landscape dukker menyelementene bak søkefeltet (kan evt. settes på linje med navn/avatar?), og flere menyvalg er ikke klikkbare fordi de er utenfor skjermen (og det ikke er mulig å scrolle).

**Comment by ksundmyhr** [comment]
Flytter siste punkt til eget issue
