### ISSUE TITLE
Standard radioknapp-komponent

### ISSUE THREAD

**Issue by MatsAnd** [vtfk/minelev-web#92]
Er behov for en radioknapp-komponent som ikke ligger i select-dropdown til bruk i YFF-tilbakemelding.
Kanskje det også er mulig å bruke igjen denne komponenten for å løse #70?

Eks av behov:
![image](https://user-images.githubusercontent.com/13292913/101986395-e120a380-3c8d-11eb-97eb-7211ff51051c.png)

**Comment by ksundmyhr** [comment]
Designmessig er det vel lagt opp til at dropdown skal brukes her. Kan den brukes i første omgang?

**Comment by MatsAnd** [comment]
Redd det blir mange klikk siden det er så mange forskjellige mål og vurderinger man må trykke seg gjennom, så jeg mistenker at det kan bli litt vel tungvindt. @zrrrzzt - hva tenker du?

**Comment by zrrrzzt** [comment]
Jeg er vel tilhenger av å bruke standardkomponenter i bunnen og så ha evt styling rundt. Nesten helt gratis UU på kjøpet.
Dropdown som er i komponentbiblioteket er vel heller ikke standard select så den burde vel også vært gjort om?
